apiVersion: v1
kind: ConfigMap
metadata:
  name: tree-env-config-map
data:
  TOKEN: "ce57d8bc990447c7ec3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treed-deployment
  labels:
    app: tree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tree
  template:
    metadata:
      labels:
        app: tree
    spec:
      containers:
      - name: tree
        image: danf/logdna-kubecon-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: tree-env-config-map
        resources:
          limits:
            cpu: "1"
            memory: "128M"
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tree-service
  labels:
    app: tree
spec:
  ports:
  - name: tree
    port: 80
    targetPort: 8080
  selector:
    app: tree
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tree
  name: tree-lb-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tree
  type: LoadBalancer
status:
  loadBalancer: {}