apiVersion: v1
kind: ConfigMap
metadata:
  name: tree-env-config-map
data:
  TOKEN: "ce57d8bc990447c7ec3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tr-k8s-demo
  labels:
    app: tree_troubleshooting_k8s_demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tree_troubleshooting_k8s_demo
  template:
    metadata:
      labels:
        app: tree_troubleshooting_k8s_demo
    spec:
      containers:
      - name: tr-k8s-demo
        image: dmontanez/logdna-kubecon-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1m"
            memory: "128M"
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tree-service
  labels:
    app: tree_troubleshooting_k8s_demo
spec:
  ports:
  - name: tree
    port: 80
    targetPort: 8080
  selector:
    app: tree_troubleshooting_k8s_demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tree_troubleshooting_k8s_demo
  name: tree-lb-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tree_troubleshooting_k8s_demo
  type: LoadBalancer
status:
  loadBalancer: {}